name: Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write
  issues: write
  packages: write
  pull-requests: write

jobs:
  release:
    name: Publish via semantic-release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
          scope: '@onlineapps'
          always-auth: true

      - name: Install dependencies
        run: npm ci

      - name: Debug checkout
        run: |
          git status
          cat .releaserc

      - name: Debug environment
        run: |
          echo "NPM_TOKEN is set: ${NPM_TOKEN:0:5}..."
          npx semantic-release --dry-run

      - name: Run tests & lint
        run: |
          npm run lint
          npm test

      - name: Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release